### ISSUE TITLE
Unable to import module 'loki-shipper': No module named 'loki-shipper'

### ISSUE THREAD

**Issue by vinga2805** [roobert/cloudwatch-loki-shipper#3]
Hi,
First of all i really want to appreciate your efforts in making the code open source.
I replicated it on my environment but somehow its not working.
I am continuously getting below error.
START RequestId: 00ad0639-ea85-462c-be78-4cb01b8e1256 Version: $LATEST
Unable to import module 'loki-shipper': No module named 'loki-shipper'
END RequestId: 00ad0639-ea85-462c-be78-4cb01b8e1256

**Comment by vinga2805** [comment]
I had made some mistake while naming handler, Now i resolved it.
I am facing below issues.



'message': KeyError
Traceback (most recent call last):
  File "/var/task/cloudwatch-loki-shipper.py", line 134, in lambda_handler
    streams = _streams(config, cloudwatch_event)
  File "/var/task/cloudwatch-loki-shipper.py", line 106, in _streams
    message = _json_message(nested_json, config, stream_labels)
  File "/var/task/cloudwatch-loki-shipper.py", line 54, in _json_message
    message, stream_labels = _template_message(nested_json, config, stream_labels)
  File "/var/task/cloudwatch-loki-shipper.py", line 47, in _template_message
    message = Template(config.log_template).substitute(**template_variables)
  File "/var/lang/lib/python3.6/string.py", line 130, in substitute
    return self.pattern.sub(convert, self.template)
  File "/var/lang/lib/python3.6/string.py", line 123, in convert
    return str(mapping[named])
KeyError: 'message'
